spring:
  application:
    name: payment-gateway

  # Use H2 in-memory database for easy testing
  datasource:
    url: jdbc:h2:mem:payment_gateway
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  # Disable Redis for now (comment out if you have Redis running)
  # redis:
  #   host: ${REDIS_HOST:localhost}
  #   port: ${REDIS_PORT:6379}
  #   password: ${REDIS_PASSWORD:}
  #   timeout: 2000ms

  # Disable Flyway for now
  flyway:
    enabled: false

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationThatShouldBeChangedInProduction123456789}
    expiration: ${JWT_EXPIRATION:3600}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.paymentgateway: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG